-- MySQL Script generated by MySQL Workbench
-- Thu Apr 20 11:59:14 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Plan-evento
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Plan-evento
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Plan-evento` DEFAULT CHARACTER SET utf8 ;
USE `Plan-evento` ;

-- -----------------------------------------------------
-- Table `Plan-evento`.`direcciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Plan-evento`.`direcciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `calle` VARCHAR(45) NULL,
  `comuna` VARCHAR(45) NULL,
  `region` VARCHAR(45) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Plan-evento`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Plan-evento`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `direccion_id` INT NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_direccion1_idx` (`direccion_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_direccion1`
    FOREIGN KEY (`direccion_id`)
    REFERENCES `Plan-evento`.`direcciones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Plan-evento`.`eventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Plan-evento`.`eventos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NULL,
  `hora_inicio` DATETIME NULL,
  `hora_fin` DATETIME NULL,
  `descripcion` TEXT NULL,
  `usuarios_id` INT NOT NULL,
  `direccion_id` INT NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_events_direccion_idx` (`direccion_id` ASC) VISIBLE,
  INDEX `fk_eventos_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_events_direccion`
    FOREIGN KEY (`direccion_id`)
    REFERENCES `Plan-evento`.`direcciones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_eventos_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `Plan-evento`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Plan-evento`.`reservas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Plan-evento`.`reservas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `comentario` VARCHAR(100) NULL,
  `usuarios_id` INT NOT NULL,
  `eventos_id` INT NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_rsvp's_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  INDEX `fk_rsvp's_eventos1_idx` (`eventos_id` ASC) VISIBLE,
  CONSTRAINT `fk_rsvp's_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `Plan-evento`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rsvp's_eventos1`
    FOREIGN KEY (`eventos_id`)
    REFERENCES `Plan-evento`.`eventos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Plan-evento`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Plan-evento`.`table1` (
)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
